{% set name = "hpp-tutorial" %}
{% set hiddenname = "hpp_tutorial" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/humanoid-path-planner/{{ hiddenname }}/releases/download/v{{ version }}/{{ hiddenname }}-{{ version }}.tar.gz
  sha256: 09d0065a2612a34780487c06603fb6a3965c7429646280f08bc825ac1a61ae7b

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - {{ cdt('mesa-libgl-devel') }}       # [linux]
    - {{ cdt('mesa-dri-drivers') }}       # [linux]
    - {{ cdt('libselinux-devel') }}       # [linux]
  host:
    - libboost-devel
    - omniorb-libs
    - hpp-core {{ version }}
    - hpp-plot {{ version }}
    - hpp-pinocchio {{ version }}
    - hpp-corbaserver {{ version }}
    - hpp-manipulation-corba {{ version }}
    - hpp-gepetto-viewer {{ version }}
    - hpp-gui {{ version }}
  run:
    - omniorb-libs

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ hiddenname }}

about:
  home: https://github.com/humanoid-path-planner/{{ hiddenname }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: {{ name }} subpackage of Humanoid Path Planner suite
  description: |
    HPP (Humanoid Path Planner) is a collection of software packages implementing
    path planning functionalities for a humanoid robot. The core functionalities are well
    suited to solve classical path planning problems. It can be extended to path planning
    for other types of robots like digital actors for instance.
  doc_url: https://gepettoweb.laas.fr/hpp/hpp-doc/doxygen-html/index.html
  dev_url: https://github.com/humanoid-path-planner/{{ hiddenname }}

extra:
  recipe-maintainers:
    - ymontmarin
